-- Preserve existing records while replacing all CUID/TEXT identifiers with UUIDs.
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- Foreign keys must be removed before their referenced and referencing columns change type.
ALTER TABLE "stores" DROP CONSTRAINT "stores_vendorId_fkey";
ALTER TABLE "products" DROP CONSTRAINT "products_storeId_fkey";
ALTER TABLE "orders" DROP CONSTRAINT "orders_customerId_fkey";
ALTER TABLE "orders" DROP CONSTRAINT "orders_storeId_fkey";
ALTER TABLE "orders" DROP CONSTRAINT "orders_deliveryPartnerId_fkey";
ALTER TABLE "orders" DROP CONSTRAINT "orders_addressId_fkey";
ALTER TABLE "order_items" DROP CONSTRAINT "order_items_orderId_fkey";
ALTER TABLE "order_items" DROP CONSTRAINT "order_items_productId_fkey";
ALTER TABLE "delivery_requests" DROP CONSTRAINT "delivery_requests_orderId_fkey";
ALTER TABLE "delivery_requests" DROP CONSTRAINT "delivery_requests_deliveryPartnerId_fkey";
ALTER TABLE "addresses" DROP CONSTRAINT "addresses_userId_fkey";
ALTER TABLE "carts" DROP CONSTRAINT "carts_userId_fkey";
ALTER TABLE "cart_items" DROP CONSTRAINT "cart_items_cartId_fkey";
ALTER TABLE "notifications" DROP CONSTRAINT "notifications_userId_fkey";

ALTER TABLE "users" DROP CONSTRAINT "users_pkey";
ALTER TABLE "stores" DROP CONSTRAINT "stores_pkey";
ALTER TABLE "products" DROP CONSTRAINT "products_pkey";
ALTER TABLE "orders" DROP CONSTRAINT "orders_pkey";
ALTER TABLE "order_items" DROP CONSTRAINT "order_items_pkey";
ALTER TABLE "delivery_requests" DROP CONSTRAINT "delivery_requests_pkey";
ALTER TABLE "addresses" DROP CONSTRAINT "addresses_pkey";
ALTER TABLE "carts" DROP CONSTRAINT "carts_pkey";
ALTER TABLE "cart_items" DROP CONSTRAINT "cart_items_pkey";
ALTER TABLE "notifications" DROP CONSTRAINT "notifications_pkey";

ALTER TABLE "users" ADD COLUMN "id_uuid" UUID NOT NULL DEFAULT gen_random_uuid();
ALTER TABLE "stores" ADD COLUMN "id_uuid" UUID NOT NULL DEFAULT gen_random_uuid(), ADD COLUMN "vendorId_uuid" UUID;
ALTER TABLE "products" ADD COLUMN "id_uuid" UUID NOT NULL DEFAULT gen_random_uuid(), ADD COLUMN "storeId_uuid" UUID;
ALTER TABLE "orders" ADD COLUMN "id_uuid" UUID NOT NULL DEFAULT gen_random_uuid(), ADD COLUMN "customerId_uuid" UUID, ADD COLUMN "storeId_uuid" UUID, ADD COLUMN "deliveryPartnerId_uuid" UUID, ADD COLUMN "addressId_uuid" UUID;
ALTER TABLE "order_items" ADD COLUMN "id_uuid" UUID NOT NULL DEFAULT gen_random_uuid(), ADD COLUMN "orderId_uuid" UUID, ADD COLUMN "productId_uuid" UUID;
ALTER TABLE "delivery_requests" ADD COLUMN "id_uuid" UUID NOT NULL DEFAULT gen_random_uuid(), ADD COLUMN "orderId_uuid" UUID, ADD COLUMN "deliveryPartnerId_uuid" UUID;
ALTER TABLE "addresses" ADD COLUMN "id_uuid" UUID NOT NULL DEFAULT gen_random_uuid(), ADD COLUMN "userId_uuid" UUID;
ALTER TABLE "carts" ADD COLUMN "id_uuid" UUID NOT NULL DEFAULT gen_random_uuid(), ADD COLUMN "userId_uuid" UUID;
ALTER TABLE "cart_items" ADD COLUMN "id_uuid" UUID NOT NULL DEFAULT gen_random_uuid(), ADD COLUMN "cartId_uuid" UUID, ADD COLUMN "productId_uuid" UUID;
ALTER TABLE "notifications" ADD COLUMN "id_uuid" UUID NOT NULL DEFAULT gen_random_uuid(), ADD COLUMN "userId_uuid" UUID;

UPDATE "stores" SET "vendorId_uuid" = "users"."id_uuid" FROM "users" WHERE "stores"."vendorId" = "users"."id";
UPDATE "products" SET "storeId_uuid" = "stores"."id_uuid" FROM "stores" WHERE "products"."storeId" = "stores"."id";
UPDATE "addresses" SET "userId_uuid" = "users"."id_uuid" FROM "users" WHERE "addresses"."userId" = "users"."id";
UPDATE "carts" SET "userId_uuid" = "users"."id_uuid" FROM "users" WHERE "carts"."userId" = "users"."id";
UPDATE "notifications" SET "userId_uuid" = "users"."id_uuid" FROM "users" WHERE "notifications"."userId" = "users"."id";
UPDATE "orders" SET "customerId_uuid" = "users"."id_uuid" FROM "users" WHERE "orders"."customerId" = "users"."id";
UPDATE "orders" SET "storeId_uuid" = "stores"."id_uuid" FROM "stores" WHERE "orders"."storeId" = "stores"."id";
UPDATE "orders" SET "deliveryPartnerId_uuid" = "users"."id_uuid" FROM "users" WHERE "orders"."deliveryPartnerId" = "users"."id";
UPDATE "orders" SET "addressId_uuid" = "addresses"."id_uuid" FROM "addresses" WHERE "orders"."addressId" = "addresses"."id";
UPDATE "order_items" SET "orderId_uuid" = "orders"."id_uuid" FROM "orders" WHERE "order_items"."orderId" = "orders"."id";
UPDATE "order_items" SET "productId_uuid" = "products"."id_uuid" FROM "products" WHERE "order_items"."productId" = "products"."id";
UPDATE "delivery_requests" SET "orderId_uuid" = "orders"."id_uuid" FROM "orders" WHERE "delivery_requests"."orderId" = "orders"."id";
UPDATE "delivery_requests" SET "deliveryPartnerId_uuid" = "users"."id_uuid" FROM "users" WHERE "delivery_requests"."deliveryPartnerId" = "users"."id";
UPDATE "cart_items" SET "cartId_uuid" = "carts"."id_uuid" FROM "carts" WHERE "cart_items"."cartId" = "carts"."id";
UPDATE "cart_items" SET "productId_uuid" = "products"."id_uuid" FROM "products" WHERE "cart_items"."productId" = "products"."id";

ALTER TABLE "stores" ALTER COLUMN "vendorId_uuid" SET NOT NULL;
ALTER TABLE "products" ALTER COLUMN "storeId_uuid" SET NOT NULL;
ALTER TABLE "orders" ALTER COLUMN "customerId_uuid" SET NOT NULL, ALTER COLUMN "storeId_uuid" SET NOT NULL;
ALTER TABLE "order_items" ALTER COLUMN "orderId_uuid" SET NOT NULL, ALTER COLUMN "productId_uuid" SET NOT NULL;
ALTER TABLE "delivery_requests" ALTER COLUMN "orderId_uuid" SET NOT NULL;
ALTER TABLE "addresses" ALTER COLUMN "userId_uuid" SET NOT NULL;
ALTER TABLE "carts" ALTER COLUMN "userId_uuid" SET NOT NULL;
ALTER TABLE "cart_items" ALTER COLUMN "cartId_uuid" SET NOT NULL, ALTER COLUMN "productId_uuid" SET NOT NULL;
ALTER TABLE "notifications" ALTER COLUMN "userId_uuid" SET NOT NULL;

ALTER TABLE "users" DROP COLUMN "id";
ALTER TABLE "users" RENAME COLUMN "id_uuid" TO "id";
ALTER TABLE "stores" DROP COLUMN "id", DROP COLUMN "vendorId";
ALTER TABLE "stores" RENAME COLUMN "id_uuid" TO "id";
ALTER TABLE "stores" RENAME COLUMN "vendorId_uuid" TO "vendorId";
ALTER TABLE "products" DROP COLUMN "id", DROP COLUMN "storeId";
ALTER TABLE "products" RENAME COLUMN "id_uuid" TO "id";
ALTER TABLE "products" RENAME COLUMN "storeId_uuid" TO "storeId";
ALTER TABLE "orders" DROP COLUMN "id", DROP COLUMN "customerId", DROP COLUMN "storeId", DROP COLUMN "deliveryPartnerId", DROP COLUMN "addressId";
ALTER TABLE "orders" RENAME COLUMN "id_uuid" TO "id";
ALTER TABLE "orders" RENAME COLUMN "customerId_uuid" TO "customerId";
ALTER TABLE "orders" RENAME COLUMN "storeId_uuid" TO "storeId";
ALTER TABLE "orders" RENAME COLUMN "deliveryPartnerId_uuid" TO "deliveryPartnerId";
ALTER TABLE "orders" RENAME COLUMN "addressId_uuid" TO "addressId";
ALTER TABLE "order_items" DROP COLUMN "id", DROP COLUMN "orderId", DROP COLUMN "productId";
ALTER TABLE "order_items" RENAME COLUMN "id_uuid" TO "id";
ALTER TABLE "order_items" RENAME COLUMN "orderId_uuid" TO "orderId";
ALTER TABLE "order_items" RENAME COLUMN "productId_uuid" TO "productId";
ALTER TABLE "delivery_requests" DROP COLUMN "id", DROP COLUMN "orderId", DROP COLUMN "deliveryPartnerId";
ALTER TABLE "delivery_requests" RENAME COLUMN "id_uuid" TO "id";
ALTER TABLE "delivery_requests" RENAME COLUMN "orderId_uuid" TO "orderId";
ALTER TABLE "delivery_requests" RENAME COLUMN "deliveryPartnerId_uuid" TO "deliveryPartnerId";
ALTER TABLE "addresses" DROP COLUMN "id", DROP COLUMN "userId";
ALTER TABLE "addresses" RENAME COLUMN "id_uuid" TO "id";
ALTER TABLE "addresses" RENAME COLUMN "userId_uuid" TO "userId";
ALTER TABLE "carts" DROP COLUMN "id", DROP COLUMN "userId";
ALTER TABLE "carts" RENAME COLUMN "id_uuid" TO "id";
ALTER TABLE "carts" RENAME COLUMN "userId_uuid" TO "userId";
ALTER TABLE "cart_items" DROP COLUMN "id", DROP COLUMN "cartId", DROP COLUMN "productId";
ALTER TABLE "cart_items" RENAME COLUMN "id_uuid" TO "id";
ALTER TABLE "cart_items" RENAME COLUMN "cartId_uuid" TO "cartId";
ALTER TABLE "cart_items" RENAME COLUMN "productId_uuid" TO "productId";
ALTER TABLE "notifications" DROP COLUMN "id", DROP COLUMN "userId";
ALTER TABLE "notifications" RENAME COLUMN "id_uuid" TO "id";
ALTER TABLE "notifications" RENAME COLUMN "userId_uuid" TO "userId";

ALTER TABLE "users" ADD CONSTRAINT "users_pkey" PRIMARY KEY ("id");
ALTER TABLE "stores" ADD CONSTRAINT "stores_pkey" PRIMARY KEY ("id");
ALTER TABLE "products" ADD CONSTRAINT "products_pkey" PRIMARY KEY ("id");
ALTER TABLE "orders" ADD CONSTRAINT "orders_pkey" PRIMARY KEY ("id");
ALTER TABLE "order_items" ADD CONSTRAINT "order_items_pkey" PRIMARY KEY ("id");
ALTER TABLE "delivery_requests" ADD CONSTRAINT "delivery_requests_pkey" PRIMARY KEY ("id");
ALTER TABLE "addresses" ADD CONSTRAINT "addresses_pkey" PRIMARY KEY ("id");
ALTER TABLE "carts" ADD CONSTRAINT "carts_pkey" PRIMARY KEY ("id");
ALTER TABLE "cart_items" ADD CONSTRAINT "cart_items_pkey" PRIMARY KEY ("id");
ALTER TABLE "notifications" ADD CONSTRAINT "notifications_pkey" PRIMARY KEY ("id");

CREATE INDEX "stores_vendorId_idx" ON "stores"("vendorId");
CREATE INDEX "products_storeId_idx" ON "products"("storeId");
CREATE INDEX "orders_customerId_idx" ON "orders"("customerId");
CREATE INDEX "orders_storeId_idx" ON "orders"("storeId");
CREATE INDEX "orders_deliveryPartnerId_idx" ON "orders"("deliveryPartnerId");
CREATE INDEX "orders_addressId_idx" ON "orders"("addressId");
CREATE INDEX "order_items_orderId_idx" ON "order_items"("orderId");
CREATE INDEX "order_items_productId_idx" ON "order_items"("productId");
CREATE INDEX "delivery_requests_orderId_idx" ON "delivery_requests"("orderId");
CREATE INDEX "delivery_requests_deliveryPartnerId_idx" ON "delivery_requests"("deliveryPartnerId");
CREATE INDEX "addresses_userId_idx" ON "addresses"("userId");
CREATE INDEX "carts_userId_idx" ON "carts"("userId");
CREATE INDEX "cart_items_cartId_idx" ON "cart_items"("cartId");
CREATE INDEX "cart_items_productId_idx" ON "cart_items"("productId");
CREATE INDEX "notifications_userId_idx" ON "notifications"("userId");

ALTER TABLE "stores" ADD CONSTRAINT "stores_vendorId_fkey" FOREIGN KEY ("vendorId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "products" ADD CONSTRAINT "products_storeId_fkey" FOREIGN KEY ("storeId") REFERENCES "stores"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "orders" ADD CONSTRAINT "orders_customerId_fkey" FOREIGN KEY ("customerId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "orders" ADD CONSTRAINT "orders_storeId_fkey" FOREIGN KEY ("storeId") REFERENCES "stores"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "orders" ADD CONSTRAINT "orders_deliveryPartnerId_fkey" FOREIGN KEY ("deliveryPartnerId") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "orders" ADD CONSTRAINT "orders_addressId_fkey" FOREIGN KEY ("addressId") REFERENCES "addresses"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "order_items" ADD CONSTRAINT "order_items_orderId_fkey" FOREIGN KEY ("orderId") REFERENCES "orders"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "order_items" ADD CONSTRAINT "order_items_productId_fkey" FOREIGN KEY ("productId") REFERENCES "products"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "delivery_requests" ADD CONSTRAINT "delivery_requests_orderId_fkey" FOREIGN KEY ("orderId") REFERENCES "orders"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "delivery_requests" ADD CONSTRAINT "delivery_requests_deliveryPartnerId_fkey" FOREIGN KEY ("deliveryPartnerId") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "addresses" ADD CONSTRAINT "addresses_userId_fkey" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "carts" ADD CONSTRAINT "carts_userId_fkey" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "cart_items" ADD CONSTRAINT "cart_items_cartId_fkey" FOREIGN KEY ("cartId") REFERENCES "carts"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "notifications" ADD CONSTRAINT "notifications_userId_fkey" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;
